server:
  port: 16899
  servlet:
    context-path: /mall

spring:
  profiles:
    include:
  datasource:
    url: jdbc:mysql://localhost:3306/security_test?useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver